/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicios;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pessoa;

/**
 *
 * @author 200901268
 */
public class View1 extends javax.swing.JFrame {

    List<Pessoa> lista;
    DefaultTableModel model;
    int[] numerosSorteados = new int[5];

    public View1() {
        initComponents();
        model = (DefaultTableModel) tbCadastro.getModel();
        lista = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtPalpite = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCadastro = new javax.swing.JTable();
        lbNome = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        lblSorteio = new javax.swing.JLabel();
        btnSortear = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        txtPalpite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalpiteKeyTyped(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        tbCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nome", "Palpite", "Diferença", "Sorteado Próximo"
            }));
            tbCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tbCadastroMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(tbCadastro);

            lbNome.setText("Nome");

            lbCPF.setText("Palpite");

            btnSortear.setText("Sortear");
            btnSortear.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSortearActionPerformed(evt);
                }
            });

            btnAtualizar.setText("Atualizar Linha");
            btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAtualizarActionPerformed(evt);
                }
            });

            btnDeletar.setText("Deletar Linha");
            btnDeletar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDeletarActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbNome)
                                .addComponent(lbCPF))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSortear, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(lblSorteio)
                                .addComponent(txtNome)
                                .addComponent(txtPalpite)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addContainerGap(56, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNome))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCPF))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCadastrar)
                    .addGap(18, 18, 18)
                    .addComponent(btnSortear)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblSorteio)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtualizar)
                        .addComponent(btnDeletar))
                    .addContainerGap(51, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa();
        p.setNome(txtNome.getText());
        p.setPalpite(Integer.parseInt(txtPalpite.getText()));

        model.addRow(new Object[]{p.getNome(), p.getPalpite()});
        limparCampos();
        verificaStatusBtn();

    }//GEN-LAST:event_btnCadastrarActionPerformed

    public void verificaStatusBtn() {
        if (model.getRowCount() >= 10) {
            btnCadastrar.setEnabled(false);
        }
    }

    public void limparCampos() {
        txtNome.setText("");
        txtPalpite.setText("");
    }

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtPalpiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalpiteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (txtPalpite.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPalpiteKeyTyped

    private void btnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearActionPerformed
        // TODO add your handling code here:
        int i = 0;
        while (i < numerosSorteados.length) {
            int numSorteado = (int) (Math.random() * 100 + 1);
            numerosSorteados[i] = numSorteado;
            i++;
        }
        ordenar();

        // Mostrar os números sorteados no lblSorteio
        StringBuilder sorteioText = new StringBuilder();
        for (int num : numerosSorteados) {
            sorteioText.append(num).append("   ");
        }
        lblSorteio.setText(sorteioText.toString().trim());

        // Percorrer as linhas da tabela e calcular a diferença
        atualizarDiferencas();

    }//GEN-LAST:event_btnSortearActionPerformed

    private void atualizarDiferencas() {
        if (vetorPreenchido()) {
            for (int j = 0; j < model.getRowCount(); j++) {
                int palpite = Integer.parseInt(model.getValueAt(j, 1).toString());
                int[] diferencaInfo = calcularDiferenca(palpite);
                int diferenca = diferencaInfo[0];
                int numeroProximo = diferencaInfo[1];
                model.setValueAt(diferenca, j, 2);
                model.setValueAt(numeroProximo, j, 3);
            }
        }
    }

    private boolean vetorPreenchido() {
        for (int num : numerosSorteados) {
            if (num == 0) {
                return false;
            }
        }
        return true;
    }

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        try {
            int linha = tbCadastro.getSelectedRow();
            model.setValueAt(txtNome.getText(), linha, 0);
            model.setValueAt(txtPalpite.getText(), linha, 1);
            tbCadastro.clearSelection();
            limparCampos();
            atualizarDiferencas();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Não foi selecionada nenhuma linha");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        try {
            model.removeRow(tbCadastro.getSelectedRow());
            limparCampos();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Não foi selecionada nenhuma linha");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tbCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCadastroMouseClicked
        // TODO add your handling code here:
        int linha = tbCadastro.getSelectedRow();
        txtNome.setText(String.valueOf(model.getValueAt(linha, 0)));
        txtPalpite.setText(String.valueOf(model.getValueAt(linha, 1)));
    }//GEN-LAST:event_tbCadastroMouseClicked

    private void ordenar() {
        int temp;
        for (int j = 1; j <= 5; j++) {
            for (int i = 0; i < 5 - 1; i++) {
                if (numerosSorteados[i] > numerosSorteados[i + 1]) {
                    temp = numerosSorteados[i];
                    numerosSorteados[i] = numerosSorteados[i + 1];
                    numerosSorteados[i + 1] = temp;
                }
            }
        }
    }

    private int[] calcularDiferenca(int valor) {
        int diferencaMinima = Integer.MAX_VALUE;
        int numeroProximo = -1;
        for (int numero : numerosSorteados) {
            int diferenca = Math.abs(numero - valor);
            if (diferenca < diferencaMinima) {
                diferencaMinima = diferenca;
                numeroProximo = numero;
            }
        }
        return new int[]{diferencaMinima, numeroProximo};
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSortear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lblSorteio;
    private javax.swing.JTable tbCadastro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPalpite;
    // End of variables declaration//GEN-END:variables
}
